In [2]:
import pandas as pd
import numpy as np

=> some part is common as SQL join, here, employeee id is common
=> NaN values are dangerous 

In [3]:


# Sample dictionaries
data1 = {
    'id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'dept': ['HR', 'Finance', 'IT', 'Marketing']
}

data2 = {
    'id': [3, 4, 5, 6],
    'salary': [70000, 80000, 65000, 60000],
    'location': ['Delhi', 'Mumbai', 'Pune', 'Bangalore']
}

data3 = {
    'id': [7, 8, 9],
    'name': ['Eve', 'Frank', 'Grace'],
    'dept': ['IT', 'Finance', 'HR']
}

# Convert to DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n", df2)
print("\nDataFrame 3:\n", df3)


DataFrame 1:
    id     name       dept
0   1    Alice         HR
1   2      Bob    Finance
2   3  Charlie         IT
3   4    David  Marketing

DataFrame 2:
    id  salary   location
0   3   70000      Delhi
1   4   80000     Mumbai
2   5   65000       Pune
3   6   60000  Bangalore

DataFrame 3:
    id   name     dept
0   7    Eve       IT
1   8  Frank  Finance
2   9  Grace       HR


In [3]:
data1=pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'dept': ['HR', 'Finance', 'IT', 'Marketing']
})

In [4]:
data1

id     name       dept
0   1    Alice         HR
1   2      Bob    Finance
2   3  Charlie         IT
3   4    David  Marketing

In [6]:

data2= pd.DataFrame({
    'id': [3, 4, 5, 6],
    'salary': [70000, 80000, 65000, 60000],
    'location': ['Delhi', 'Mumbai', 'Pune', 'Bangalore']
})

data2


id  salary   location
0   3   70000      Delhi
1   4   80000     Mumbai
2   5   65000       Pune
3   6   60000  Bangalore

In [5]:
employees =pd.DataFrame( {
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries =pd.DataFrame( {
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})



In [10]:
employees



employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [11]:
salaries 

employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [7]:
pd.merge (employees, salaries,on='employee_id') #=> on the basis of which

employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [8]:
pd.merge (employees, salaries,on='employee_id' , how='inner') #=> on the basis of which

employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

# 1️⃣ Inner Join

=> inner means only keep rows where the key matches in both DataFrames.

In [9]:
import pandas as pd

employees = pd.DataFrame({
    'employee_id': [1, 2, 3],
    'name': ['Sakshi', 'Riya', 'Aman']
})

salaries = pd.DataFrame({
    'employee_id': [2, 3, 4],
    'salary': [50000, 60000, 55000]
})

result = pd.merge(employees, salaries, on='employee_id', how='inner')
print(result)


   employee_id  name  salary
0            2  Riya   50000
1            3  Aman   60000


🔎 What Happened?

employee_id = 1 (Sakshi) was dropped → because no salary record exists. 2-Riya and 3-Aman has salary record only

employee_id = 4 (salary data) was dropped → because no employee record exists.

Only IDs 2 & 3 exist in both DataFrames, so they appear in the result.

# 2️⃣ LEFT JOIN
=> Keep all from left (employees), match if possible

In [10]:
pd.merge(employees,salaries, on='employee_id', how='left')

employee_id    name   salary
0            1  Sakshi      NaN
1            2    Riya  50000.0
2            3    Aman  60000.0

✔ All employees kept.
✔ Sakshi (ID=1) has no salary → shows NaN.

# 3️⃣ RIGHT JOIN 
→ Keep all from right (salaries), match if possible
→ employees & salaries are given - right is salaries so on the basis of salaries

In [11]:
pd.merge(employees,salaries, on='employee_id',how='right')

employee_id  name  salary
0            2  Riya   50000
1            3  Aman   60000
2            4   NaN   55000

✔ All salaries kept.
✔ ID=4 has no matching employee → name is NaN.

# 4️⃣ OUTER JOIN
→ Keep all from both sides

In [12]:
pd.merge(employees,salaries , on='employee_id' , how='outer')

employee_id    name   salary
0            1  Sakshi      NaN
1            2    Riya  50000.0
2            3    Aman  60000.0
3            4     NaN  55000.0

✔ Combines everything.
✔ Missing values filled with NaN.

| Join Type | What You Get                       |
| --------- | ---------------------------------- |
| **Inner** | Only matching rows                 |
| **Left**  | All from left + matches from right |
| **Right** | All from right + matches from left |
| **Outer** | All rows from both sides           |


# concatination of 2 DataFrames
=> takes multiple Datas in a list

In [6]:
import pandas as pd

In [7]:

df1=pd.DataFrame( {
    'employee_id': [1, 2, 3],
    'name': ['John', 'Anna', 'Peter'],
    'department': ['HR', 'IT', 'Finance']
})
df2=pd.DataFrame( {
    'employee_id': [4, 5, 6],
    'name': ['Linda', 'Bob', 'Sophie'],
    'department': ['IT', 'HR', 'Finance']
})



In [8]:
df1

employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance

In [9]:
df2

employee_id    name department
0            4   Linda         IT
1            5     Bob         HR
2            6  Sophie    Finance

In [10]:
pd.concat([df1,df2])

employee_id    name department
0            1    John         HR
1            2    Anna         IT
2            3   Peter    Finance
0            4   Linda         IT
1            5     Bob         HR
2            6  Sophie    Finance

In [11]:
pd.concat([df2,df1]) #df2 upper

employee_id    name department
0            4   Linda         IT
1            5     Bob         HR
2            6  Sophie    Finance
0            1    John         HR
1            2    Anna         IT
2            3   Peter    Finance

In [12]:
import pandas as pd
pd.concat([df1,df2],axis=1) # on the basis of rows

employee_id   name department  employee_id    name department
0            1   John         HR            4   Linda         IT
1            2   Anna         IT            5     Bob         HR
2            3  Peter    Finance            6  Sophie    Finance

# Joining 2 DataFrames
=>join matches on index.

In [18]:
# DataFrame 1
df1 = pd.DataFrame({
    'name': ['Sakshi', 'Riya', 'Aman'],
    'department': ['HR', 'Finance', 'IT']
}, index=[101, 102, 103])

# DataFrame 2
df2 = pd.DataFrame({
    'salary': [50000, 60000, 55000],
    'bonus': [5000, 7000, 6000]
}, index=[101, 102, 104])



In [19]:
df1

name department
101  Sakshi         HR
102    Riya    Finance
103    Aman         IT

In [20]:
df2

salary  bonus
101   50000   5000
102   60000   7000
104   55000   6000

In [21]:
df1.join(df2)

name department   salary   bonus
101  Sakshi         HR  50000.0  5000.0
102    Riya    Finance  60000.0  7000.0
103    Aman         IT      NaN     NaN


1)Join is index-based by default → It matches rows of df1 and df2 using their index values.
2)For indices that exist in both DataFrames, you get merged data.
3)For indices that are only in df1 but missing in df2 → you get NaN (like Aman with index 103).
4)For indices that are in df2 but missing in df1 (like 104) → those rows are not included, since join keeps df1's index by default.(104)